version: '3'

services:
  app:
    container_name: appMarvel
    restart: always
    build: .
    ports: 
      - "4000:3000"
    links:  
      - db
  db:
    container_name: dbMarvel
    image: mongo
    ports: 
      - "27017:27017"