version: '3'

services:
  app:
    container_name: backMarvel
    restart: always
    build: .
    ports: 
      - "4000:3000"
    links:  
      - db
    volumes:
      - .:/usr/src/app
  db:
    container_name: dbMarvel
    image: mongo
    ports: 
      - "27017:27017"